Create codeql.yml (#68)
apparently we need codeql so this will work as a transitive dep in compass

Error: Failed to get SARIF for repository {"owner":"mongodb-js","repo":"atlas-local-lib-js","forPackage":"@mongodb-js/atlas-local-linux-x64-gnu","packageVersion":"1.1.0","commit":"5bf4141f4861554d42877588b2b93de3ea63b960"}: HttpError: no analysis found - https://docs.github.com/rest/code-scanning/code-scanning#list-code-scanning-analyses-for-a-repository